### ISSUE TITLE
Issue with data path and compilation

### ISSUE THREAD

**Issue by LIQiushui2427** [ZhengfanCMU/15618_project#2]
Hello i'm compiling your repo, and i put 4 datasets in src/data/.
![Screenshot from 2022-09-20 10-21-09](https://user-images.githubusercontent.com/83109207/191153040-ecb94350-220f-4f89-bcac-beb0b24395cb.png)
 But it seems that the dataloader function still can't find the files.
Here is the log:
cudaNeuron: main.cpp:108: void load_MNIST(const char*, const char*, uint8_t*&, uint8_t*&): Assertion `mnistImageFile != NULL' failed.
Aborted (core dumped)
![Screenshot from 2022-09-20 10-15-41](https://user-images.githubusercontent.com/83109207/191152931-ec31e57a-a1ff-475c-8b9c-b55301f3b5b4.png)
Besides, when i tried to recompile for debug purpose, ghc can't find Makefile module (while the file and be detected)
Here is the log:
<no location info>: error:
    module ‘Makefile’ cannot be found locally
![Screenshot from 2022-09-20 10-22-06](https://user-images.githubusercontent.com/83109207/191153176-c8c11051-4b04-4fbd-a485-c1dc231098dd.png)
Thank you for your attention.

**Comment by hongxuanlcmu** [comment]
we are just using plain makefile though, I have no idea if that works with ghc. Could you just modify the Makefile and run make?
You can change the assert to an if condition and do `perror("")` to see the reason file open failed, maybe also printf `(dirpath+mnistTestImgPath).c_str()` in the main function to see what is the complete path you are getting

**Comment by ZhengfanCMU** [comment]
This project is a CMU 15618 course final project, and is supposed to be run on CMU's GHC cluster with its setup (I think the course provided a setup script for the CUDA on GHC). You need to follow the course's setup instructions.

And as for the dataloader's problem, please check the source code to see if the correct files are placed in the correct directory.

**Comment by lyccyl1** [comment]
sir, could u plz provide the  setup script for the CUDA on GHC.  I can't find it.

**Comment by hongxuanlcmu** [comment]
I think you just have to have CUDA installed. https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by ZhengfanCMU** [comment]
Sorry, but I currently cannot access ghc machines due to some unknown issues and cannot go through the setup process.
Here is the setup process for one of the course's assignment-2 that uses cuda, ith. You may have to use vpn to connect to cmu first.

Environment Setup
You should use the GHC machines containing NVIDIA GeForce RTX 2080 B GPUs. These have host
names ghcX.ghc.andrew.cmu.edu, for X between 47 and 86. The Wikipedia entry for GeForce 20
GPUs provides useful information about this model of GPU. They support CUDA compute capability 7.5.
1
Using the GHC machines:
1. If you are using the ssh command to reach the machine, include the option “-Y” in your command
line to enable the use of X windows.
2. The NVIDIA CUDA C/C++ Compiler (NVCC) is located at /usr/local/depot/cuda/bin/,
which you need to add to your PATH. To do this, add the line below to the file below, according
to which shell you use. (You can determine which shell you are using with the command “echo
$SHELL.”)
Shell File Add
bash ˜/.bashrc export PATH=/usr/local/depot/cuda/bin:${PATH}
csh ˜/.cshrc setenv PATH /usr/local/depot/cuda/bin:${PATH}
3. The CUDA shared library is located at /usr/local/depot/cuda/lib64/. It must be loaded
at runtime. Add the line below to your RC file (˜/.bashrc or ˜/.cshrc) according to which
shell you use.
export LD_LIBRARY_PATH=/usr/local/depot/cuda/lib64/:${LD_LIBRARY_PATH}
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/local/depot/cuda/lib64/
4. Make sure you source (or reload) your RC file. If using bash, run “source ˜/.bashrc.” If using
csh, run “source ˜/.cshrc.”

**Comment by lyccyl1** [comment]
aha , sorry I haven't the vpn connect to the cmu.  This is our course's final project to recurrent your project ahaha. Thank you guys for replying. xiexie nimen
